### ISSUE TITLE
Technincal review

### ISSUE THREAD

**Issue by HelgaListopad** [LukshaMaria/Projects-Webix#1]
Добрый день и большое спасибо за то, что выполнили тестовое.

Результат выглядит вполне хорошо, но есть некоторые вещи, которые можно упростить - для них я оставляю комментарии с примерами.
Это не запрос на обязательные правки. На своё усмотрение Вы можете либо внести изменения в код, либо оставить как есть.

С небольшими изменениями пример может стать таким:
https://snippet.webixcode.com/mf/xsbdo7st
Исходный код здесь:
https://snippet.webix.com/xsbdo7st
Ниже я поясню изменения двух основных вещей: 
<details>
<summary>Размерность</summary>
<br/>

Основная часть UI фиксированной высоты из-за `height: 650` в этой строчке и ещё нескольких настроек (у формы и таблицы):
https://github.com/LukshaMaria/Projects-Webix/blob/674f74d2014138bc02a8ea11cc6e95a2b69fb82c/task-webix-1/task-webix.html#L55
Было бы лучше, если бы UI мог хоть немного подстраиваться под высоту страницы, иначе часть элементов при уменьшении размера окна уйдёт в overflow.
Но если убрать тут `height`, то верхняя половина сожмётся до размеров формы. Для этого есть две причины:
- у формы внутри только элементы с фиксированной высотой (текстовые поля и кнопки), и её общая высота подстраивается под них,
- у таблицы есть свойство `autoheight`.

И то, и другое заставляет всю строку сжиматься под минимально возможный размер.
Решить это можно, убрав `autoheight` и добавив spacer (`{ }`) последним элементом в форму (например, вы верно сделали это в левой части, между листом и кнопкой).
</details>
<details>
<summary>Стилизация</summary>
<br/>
Фон можно применить ко всей левой части - это решение будет более оптимальным, чем добавление css каждому виджету отдельно.

```js
var menu = {
  css: "list",
  rows: []
}
```

Обратите внимание, что в snippet'e выше появился новый CSS-селектор (`.webix_list_item` для строк в листе)
```css
  .list, 
  .list .webix_list_item {
    background-color: #eeeeee;
  }
```
<hr>

Для подписи Connected вы использовали кнопку, но в таком случае остаются стили кнопки для `hover`. Кроме того, можно не задавать ей ширину.
https://github.com/LukshaMaria/Projects-Webix/blob/674f74d2014138bc02a8ea11cc6e95a2b69fb82c/task-webix-1/task-webix.html#L29

Сюда больше подойдёт label (его фон прозрачный, поэтому в стилях достаточно указать цвет текста)

```js
    { 
      view: "label",
      css: "connected",   // color: green;
      align: "center",
      label: `<span class="webix_icon mdi mdi-check"></span> Connected`, 
    },
```

</details>

<br/>

И последнее:

В этом месте вызов `form.save()` лишний, так как сам по себе ничего не делает
https://github.com/LukshaMaria/Projects-Webix/blob/674f74d2014138bc02a8ea11cc6e95a2b69fb82c/task-webix-1/task-webix.html#L44

Но он может использоваться для сохранения, если есть [связь](https://docs.webix.com/desktop__data_binding.html) между таблицей и формой, как в этом коротком примере (строка 38): https://snippet.webix.com/b1l5kdop

Спасибо!

**Comment by LukshaMaria** [comment]
Спасибо!

пн, 20 июн. 2022 г. в 10:50, Helga Listopad ***@***.***>:

**Comment by LukshaMaria** [comment]
Здравствуйте, спасибо за комментарии! Всё поняла, изменения внесла.

пн, 20 июн. 2022 г. в 12:10, Маша Лукша ***@***.***>:
